# Generated by Django 4.2.5 on 2023-09-06 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성 여부")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="갱신일")),
                ("title", models.TextField(max_length=250, verbose_name="제목")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=250,
                        unique=True,
                        unique_for_date="publish",
                        verbose_name="슬러그",
                    ),
                ),
                ("body", models.TextField(verbose_name="본문")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Published")],
                        default=0,
                        verbose_name="게시상태",
                    ),
                ),
                ("publish", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "게시글",
                "verbose_name_plural": "게시글 목록",
                "ordering": ["-publish"],
            },
        ),
    ]
