# Generated by Django 4.2.5 on 2023-09-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["-like_count"], name="posts_comme_like_co_2adfa5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-like_count"], name="posts_post_like_co_fdd79b_idx"
            ),
        ),
    ]
