# Generated by Django 4.2.5 on 2023-09-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0009_comment_like_count_post_like_count_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id", "user"), name="unique_like"
            ),
        ),
    ]
