# Generated by Django 4.2.5 on 2023-09-06 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성 여부")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="갱신일")),
                (
                    "email",
                    models.EmailField(max_length=100, unique=True, verbose_name="이름"),
                ),
                ("fullname", models.TextField(max_length=30, verbose_name="이름")),
                (
                    "phone",
                    models.TextField(max_length=30, unique=True, verbose_name="휴대폰번호"),
                ),
                ("password", models.CharField(max_length=100, verbose_name="비밀번호")),
                ("is_admin", models.BooleanField(default=False, verbose_name="관리자여부")),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자 목록",
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "user_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="팔로우 한 유저",
                    ),
                ),
                (
                    "user_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="팔로우 받은 유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "팔로우 관계",
                "verbose_name_plural": "팔로우 관계 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                related_name="followers",
                through="users.Follow",
                to=settings.AUTH_USER_MODEL,
                verbose_name="팔로우",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성 여부")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="갱신일")),
                ("nickname", models.TextField(max_length=30, verbose_name="닉네임")),
                ("birthday", models.DateField(verbose_name="생년월일")),
                (
                    "image_url",
                    models.URLField(blank=True, null=True, verbose_name="프로필사진"),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="공개여부")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "프로필",
                "verbose_name_plural": "프로필 목록",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["-updated_at"], name="users_profi_updated_bab9cc_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["-created_at"], name="users_follo_created_93906d_idx"
            ),
        ),
    ]
