# Generated by Django 4.2.5 on 2023-09-08 06:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_options_alter_profile_nickname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                related_name="follower",
                through="users.Follow",
                to=settings.AUTH_USER_MODEL,
                verbose_name="팔로우",
            ),
        ),
    ]
