# Generated by Django 4.2.5 on 2023-09-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="공개여부"),
        ),
    ]
