#!/bin/bash

# collectstatic 진행
echo "collectstatic 진행"
python manage.py collectstatic --no-input

# migrate 진행
echo "migrate 진행"
python manage.py migrate

# gunicorn 실행
echo "gunicorn 실행"
gunicorn config.wsgi:application -c config/gunicorn_config.py