name: CD to staging server using Docker Image

on:
    workflow_dispatch:
    # pull_request:
    #     types:
    #         - closed
    #     branches:
    #         - develop
    #     paths-ignore:
    #         - 'README.md'
    #         - 'docker/**'
    #         - 'infra/**'
    #         - 'script/**'
    #         - '.github/workflows/01_CI.yaml'
    #         - '.github/workflows/03_CICD_to_prod.yaml'


env:
    IMAGE: ${{ vars.NCR_HOST }}/swns
    IMAGE_TAG: ${{ vars.NCR_HOST }}/swns:latest
    CONTAINER_NAME: be-staging

jobs:
    deploy-staging:
        name: deploy to staging
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
            - name: pull and run the image
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ vars.NCP_HOST_STAGING }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: |
                      docker login \
                      ${{ vars.NCR_HOST }} \
                      -u ${{ secrets.NCP_ACCESS_KEY }} \
                      -p ${{ secrets.NCP_SECRET_KEY }}
                      docker pull ${{ env.IMAGE_TAG }}
                      docker stop ${{ env.CONTAINER_NAME }} && docker rm ${{ env.CONTAINER_NAME }}
                      docker run -d -p 8000:8000 \
                      --env-file .env \
                      --name ${{ env.CONTAINER_NAME }} \
                      ${{ env.IMAGE_TAG }}
